export interface GameProvider {
  id: string;
  name: string;
}

export const GAME_PROVIDERS: GameProvider[] = [
  { id: "netent", name: "NetEnt" },
  { id: "evolution", name: "Evolution" },
  { id: "pragmatic-play", name: "Pragmatic Play" },
  { id: "microgaming", name: "Microgaming" },
  { id: "playngo", name: "Play'n GO" },
  { id: "yggdrasil", name: "Yggdrasil" },
  { id: "red-tiger", name: "Red Tiger" },
  { id: "big-time-gaming", name: "Big Time Gaming" },
  { id: "nolimit-city", name: "Nolimit City" },
  { id: "push-gaming", name: "Push Gaming" },
  { id: "relax-gaming", name: "Relax Gaming" },
  { id: "hacksaw-gaming", name: "Hacksaw Gaming" },
  { id: "elk-studios", name: "ELK Studios" },
  { id: "thunderkick", name: "Thunderkick" },
  { id: "quickspin", name: "Quickspin" },
  { id: "isoftbet", name: "iSoftBet" },
  { id: "blueprint-gaming", name: "Blueprint Gaming" },
  { id: "endorphina", name: "Endorphina" },
  { id: "betsoft", name: "Betsoft" },
  { id: "evoplay", name: "Evoplay" },
  { id: "wazdan", name: "Wazdan" },
  { id: "playtech", name: "Playtech" },
  { id: "novomatic", name: "Novomatic" },
  { id: "amatic", name: "Amatic" },
  { id: "igt", name: "IGT" },
  { id: "scientific-games", name: "Scientific Games" },
  { id: "aristocrat", name: "Aristocrat" },
  { id: "ainsworth", name: "Ainsworth" },
  { id: "habanero", name: "Habanero" },
  { id: "booongo", name: "Booongo" },
  { id: "bgaming", name: "BGaming" },
  { id: "spribe", name: "Spribe" },
  { id: "1x2-gaming", name: "1x2 Gaming" },
  { id: "iron-dog-studio", name: "Iron Dog Studio" },
  { id: "kalamba-games", name: "Kalamba Games" },
  { id: "fantasma-games", name: "Fantasma Games" },
  { id: "peter-and-sons", name: "Peter & Sons" },
  { id: "gaming-corps", name: "Gaming Corps" },
  { id: "spinomenal", name: "Spinomenal" },
  { id: "pragmatic-play-live", name: "Pragmatic Play Live" },
  { id: "ezugi", name: "Ezugi" },
  { id: "playson", name: "Playson" },
  { id: "tom-horn", name: "Tom Horn" },
  { id: "stakelogic", name: "Stakelogic" },
  { id: "gamomat", name: "Gamomat" },
  { id: "4theplayer", name: "4ThePlayer" },
  { id: "avatar-ux", name: "AvatarUX" },
  { id: "print-studios", name: "Print Studios" },
  { id: "true-lab", name: "True Lab" },
  { id: "swintt", name: "Swintt" },
  { id: "netgame", name: "NetGame" },
  { id: "gamebeat", name: "Gamebeat" },
  { id: "mascot-gaming", name: "Mascot Gaming" },
  { id: "gamzix", name: "Gamzix" },
  { id: "belatra", name: "Belatra" },
  { id: "fugaso", name: "Fugaso" },
  { id: "ct-gaming", name: "CT Gaming" },
  { id: "leap-gaming", name: "Leap Gaming" },
  { id: "3-oaks-gaming", name: "3 Oaks Gaming" },
  { id: "spearhead-studios", name: "Spearhead Studios" },
];

export function getGameProviderName(id: string): string {
  const provider = GAME_PROVIDERS.find((p) => p.id === id);
  return provider?.name || id;
}
